store/config/routes.rb
Store::Application.routes.draw do |map|
  resources :categories
  resources :products
  root :to => "products#index"
end

store/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

store/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      render :action => 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed category."
    redirect_to categories_url
  end
end

store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to @product
    else
      render :action => 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      flash[:notice] = "Successfully updated product."
      redirect_to @product
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_url
  end
end

store/app/helpers/application_helper.rb
module ApplicationHelper
end

store/app/helpers/categories_helper.rb
module CategoriesHelper
end

store/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @_content_for[:title] = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

store/app/helpers/products_helper.rb
module ProductsHelper
end

store/app/views/categories/_form.html.erb
<% form_for @category do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

store/app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

store/app/views/categories/index.html.erb
<% title "Categories" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for category in @categories %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to "Show", category %></td>
      <td><%= link_to "Edit", edit_category_path(category) %></td>
      <td><%= link_to "Destroy", category, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Category", new_category_path %></p>

store/app/views/categories/new.html.erb
<% title "New Category" %>

<%= render 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

store/app/views/categories/show.html.erb
<% title "Category" %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categories_path %>
</p>

store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "jquery.rails.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

store/app/views/products/_form.html.erb
<% form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

store/app/views/products/_product.html.erb
<div class="product">
  <h3>
    <%= link_to product.name, product %>
    <%= number_to_currency(product.price) %>
  </h3>
  <div class="actions">
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Destroy", product, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

store/app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

store/app/views/products/index.html.erb
<% title "Products" %>

<% form_tag products_path, :method => :get, :remote => true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<div id="products">
  <%= render @products %>
</div>

<p><%= link_to "New Product", new_product_path %></p>

store/app/views/products/index.js.erb
$("#products").html("<%= escape_javascript(render(@products)) %>");

store/app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

store/app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<% unless @product.category.nil? %>
<p>
  <strong>Category:</strong>
  <%= link_to @product.category.name, @product.category %>
</p>
<% end %>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => "Are you sure?", :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>